name: Test
on: workflow_dispatch
jobs:
  print:
    runs-on: windows-2019
    steps:
     - uses: actions/checkout@v3
     - name: build
       run: dotnet build --configuration Release
     - name: test
       run: dotnet test ./UnitTestProject/bin/Release/UnitTestProject.dll
     - uses: actions/upload-artifact@v3
       with:
        name: my-artifact
        path: ./GitHubActinTest/bin/Release
     - uses: ncipollo/release-action@v1
       with:
        artifacts: "release.tar.gz,foo/*.txt"
        bodyFile: my-artifact.zip
     
