name: Test
on: workflow_dispatch
jobs:
  print:
    runs-on: windows-2019
    steps:
    - name: load code
    - uses: actions/checkout@v
    - name: build project
    - uses: EasyDesk/action-dotnet-build@v1
      with:
          # (Optional) Additional arguments for dotnet build.
           build-args: -v normal

          # (Optional) Build configuration, defaults to 'Release'
          # If the version starts with the 'v' prefix, it will be removed to conform to the requirements of dotnet pack.
           build-configuration: Release

          # (Optional) The path of the project to build; if omitted, the whole solution is built
           path: ./GitHubActinTest.sln   
