name: Test
on: workflow_dispatch
jobs:
  print:
    runs-on: windows-2019
    steps:
     - uses: actions/checkout@v3
     - name: build
       run: dotnet build --configuration Release
     - name: test
       run: dotnet test --no-restore --verbosity normal
     - uses: actions/upload-artifact@v3
       with:
        name: my-artifact
        path: ./GitHubActinTest/bin/Release
     - uses: potatoqualitee/mssqlsuite@v1.7
       with:
          install: sqlengine, sqlclient, sqlpackage
          version: 2017
          sa-password: c0MplicatedP@ssword
          show-log: true
          collation: Latin1_General_BIN
     - name: Run sqlcmd
       run: sqlcmd -S localhost -U sa -P c0MplicatedP@ssword -d tempdb -Q "SELECT @@version;"

     
