name: Test
on: workflow_dispatch
jobs:
  print:
    runs-on: windows-2019
    steps:
     - uses: actions/checkout@v3
     - name: my build
       run: dotnet msbuild -property:Configuration=Release
      
